### ISSUE TITLE
Grafana error: Could not find webhook url property in settings

### ISSUE THREAD

**Issue by ThomasDalla** [livepeer/docker-livepeer#84]
Fails to start Grafana with the following error:
```
service init failed: Alert notification provisioning error: alert validation error: Could not find webhook url property in settings
```

My docker-compose config:
```yaml
services:
  livepool_monitor:
    container_name: livepool_monitor
    image: livepeer/monitoring:latest
    #network_mode: host
    ports:
      - '9191:9090'
      - '3001:3000'
    environment:
      LP_MODE: 'standalone'
      LP_NODES: '127.0.0.1:7935'
      LP_PROMETHEUS_ENDPOINT: 'http://localhost:9191'
    volumes:
      - ./livepool_monitoring/log:/var/log/grafana
      - ./livepool_monitoring/data:/data
      - ./livepool_monitoring/data/plugins:/etc/grafana/provisioning/plugins # hack to pass issue #83
```
